# This config file is optional!!! If this file exists next to the .sh file, it's loaded by the script.
# You can delete this file to use the built-in defaults. Up to you :3





# RiftLift's game slug. To get your game's slug, run `riftlift list`
SLUG="echo-vr"

# How many relaunch rounds to attempt before the script stops itself.
MAX_LAUNCHES="25"

# Where RiftLift's Proton log lives. Leave blank to use the default, which is TYPICALLY ~/.local/share/riftlift/diagnostics/proton/steam-0.log
# Override this if you want or need to
RIFTLIFT_LOG=""

# Where to store dumped/patched shaders. Leave blank to use my defaults
SHADER_ROOT_OVERRIDE=""
